name: Push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bot_anatoly:latest
      -
        name: Deploy new container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f botAnatoly
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/bot_anatoly:latest
            docker run -d -e BOT_TOKEN=${{ secrets.PROD_BOT_TOKEN }} --name botAnatoly ${{ secrets.DOCKER_HUB_USERNAME }}/bot_anatoly:latest
